[[main]]
  name = "首页"
  pageRef = "/"
  weight = 10



[[main]]
  name = "文章"
  pageRef = "/posts"
  weight = 20

[[main]]
  name = "阅读小记"
  pageRef = "/posts/read"
  parent="文章"
  weight = 20

[[main]]
  name = "嘉豪日记"
  pageRef = "/posts/jiahao"
  parent="文章"
  weight = 20

[[main]]
  name = "美食寻迹"
  pageRef = "/posts/td"
  parent="文章"
  weight = 20

[[main]]
  name = "ACM"
  weight = 20

[[main]]
  name = "abc"
  weight =3
  parent = "ACM"
  pageRef = "/acm/ABC"

[[main]]
  name = "Codeforces"
  weight =2
  parent = "ACM"
  pageRef = "/acm/cf"

[[main]]
  name = "算法"
  weight =4
  parent = "ACM"
  pageRef = "/acm/算法"

[[main]]
  name = "标签"
  pageRef = "/tags"
  weight = 30

[[main]]
  name = "关于"
  pageRef = "/about"
  weight = 40