[[main]]
  name = "首页"
  pageRef = "/"
  weight = 10

[[main]]
  name = "文章"
  pageRef = "/posts"
  weight = 20

[[main]]
  name = "ACM"
  weight = 20

[[main]]
  name = ""
  weight =1
  parent = "ACM"
  pageRef = "/BLOG1"

[[main]]
  name = ""
  weight =2
  parent = "ACM"
  pageRef = "/blog"

[[main]]
  name = "标签"
  pageRef = "/tags"
  weight = 30

[[main]]
  name = "关于"
  pageRef = "/about"
  weight = 40