colorScheme = "blowfish"
defaultAppearance = "dark"
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true

showReadingTime = true
showTableOfContents = true
showAuthor = true
[homepage]
  homepageImage = "img/background.jpg"
  layout = "background"
  # layout = "background"
  # 如果想要启用 custom 布局，请在 params.toml 配置文件中设置 homepage.layout = "custom" 。
  # 配置好参数后，在 layouts/partials/home 目录下创建一个 custom.html 文件。 
  # custom.html 文件中定义的任何内容都会被放置在网站主页的内容区域。你可以使用 HTML、Tailwind 或 Hugo 模板函数来定义你的布局。
  # 如果你想在自定义布局上添加 最近文章，请使用 recent-articles/main.html 中的内容。

  showRecent = true
  showRecentItems = 15
  cardView = true

[article]
  showDate = true
  showDateUpdated = true
  showAuthor = true
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = true
  showHeadingAnchors = true
  showPagination = true
  showEdit = false
  showLikes = false
  showComments = false
  showHero = true

[assets]
  disableHLJS = true


[list]
  cardView=true

customCSS = ["css/custom.css"]
